// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;
using namespace arma;
using namespace std;

// lCox
vec lCox(const vec& beta, const vec& y, const mat& x, const vec& str);
RcppExport SEXP _st4sas_lCox(SEXP betaSEXP, SEXP ySEXP, SEXP xSEXP, SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const vec& >::type str(strSEXP);
    rcpp_result_gen = Rcpp::wrap(lCox(beta, y, x, str));
    return rcpp_result_gen;
END_RCPP
}
// grCox
rowvec grCox(const vec& beta, const vec& y, const mat& x, const vec& str);
RcppExport SEXP _st4sas_grCox(SEXP betaSEXP, SEXP ySEXP, SEXP xSEXP, SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const vec& >::type str(strSEXP);
    rcpp_result_gen = Rcpp::wrap(grCox(beta, y, x, str));
    return rcpp_result_gen;
END_RCPP
}
// hessCox
mat hessCox(const vec& beta, const vec& y, const mat& x, const vec& str);
RcppExport SEXP _st4sas_hessCox(SEXP betaSEXP, SEXP ySEXP, SEXP xSEXP, SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const vec& >::type str(strSEXP);
    rcpp_result_gen = Rcpp::wrap(hessCox(beta, y, x, str));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_st4sas_lCox", (DL_FUNC) &_st4sas_lCox, 4},
    {"_st4sas_grCox", (DL_FUNC) &_st4sas_grCox, 4},
    {"_st4sas_hessCox", (DL_FUNC) &_st4sas_hessCox, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_st4sas(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
