# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lCox <- function(beta, y, x, str) {
    .Call(`_st4sas_lCox`, beta, y, x, str)
}

grCox <- function(beta, y, x, str) {
    .Call(`_st4sas_grCox`, beta, y, x, str)
}

hessCox <- function(beta, y, x, str) {
    .Call(`_st4sas_hessCox`, beta, y, x, str)
}

